//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long OID { get; set; }
        public string MemberName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public string AddressOne { get; set; }
        public string NIDorBIN { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string ContactPersonName { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string ConcatPersonEmail { get; set; }
        public string AddressTwo { get; set; }
        public string Nationality { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
        public Nullable<decimal> OverDueAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
